### ISSUE TITLE
Why its showing excluded in hacktoberfest2022?? 

### ISSUE THREAD

**Issue by aritroo** [niteshjitender/HacktoberFest2022#23]
PR is showing in hacktoberfest 2022

![Screenshot 2022-10-01 160550](https://user-images.githubusercontent.com/91552411/193405508-f84a3e73-5001-4343-b64f-41003e0b1d19.png)

**Comment by niteshjitender** [comment]
There are some new guidelines, which say simple changes in documentation will not be considered a good PR.
So that's why is showing excluded.

**Comment by niteshjitender** [comment]
You can go to the readme section and make some changes as suggested or can review the issue section if there is anything in which you can contribute.

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

**Comment by niteshjitender** [comment]
Hi @ItzLevvie 
Thank you for the updates. I have updated the repository readme file with a similar message.
